# Generated by Django 4.2.1 on 2023-06-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_wishlist_userwish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='userwish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
