# Generated by Django 4.2.1 on 2023-06-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_wishlist_userwish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='userwish',
        ),
    ]
