# Generated by Django 4.2.1 on 2023-06-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_wishlisttwo_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlisttwo',
            name='userwish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
