# Generated by Django 4.2.1 on 2023-06-26 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_alter_wishlisttwo_userwish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlisttwo',
            name='userwish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
