# Generated by Django 4.2.1 on 2023-06-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_wishlisttwo_userwish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlisttwo',
            name='userwish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.profile'),
        ),
    ]
